Negotiate docker API version in KVM compliance tests
After an update of docker client, the tests atsrted failing with
```
    --- FAIL: TestCompliance/compliance-nginx (0.01s)
        compliance.go:246: building test nginx-compliance-test:latest...
        compliance_test.go:77:
            	Error Trace:	/host/hubble-fgs/tests/compliance/compliance_test.go:77
            	Error:      	Received unexpected error:
            	            	failed to build image: Error response from daemon: client version 1.46 is too new. Maximum supported API version is 1.45
            	Test:       	TestCompliance/compliance-nginx
```

Signed-off-by: Anna Kapuscinska <anna@isovalent.com>