pkg/netpolstate: fix concurent map iteration/write
It appears that while iterating the map when deep copying the Pod object
from the Reconcile loop of the pkg/workloadid, another part of the
program is trying to write to the object.

We have a situation in which we actually mutate the Pod cache
information by adding labels to the object instead of doing that on a
copy.  We have other instances where we retrieve the Pod labels, but it
seems to me that we only read from it.

Note that I took the occasion to clean up the addNamespaceLabels method.

The stack trace dump from the panic looked like that:

	fatal error: concurrent map iteration and map write

	goroutine 583 [running]:
	internal/runtime/maps.fatal({0x379f56e?, 0x1359e2c24d40?})
		/usr/local/go/src/runtime/panic.go:1181 +0x18
	internal/runtime/maps.(*Iter).Next(0x1359e5207598?)
		/usr/local/go/src/internal/runtime/maps/table.go:819 +0x86
	k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).DeepCopyInto(0x1359e3ea6028, 0x1359e3ea6f28)
		/go/src/github.com/isovalent/hubble-fgs/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/zz_generated.deepcopy.go:708 +0x285
	k8s.io/api/core/v1.(*Pod).DeepCopyInto(0x1359e3ea6008, 0x1359e3ea6f08)
		/go/src/github.com/isovalent/hubble-fgs/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3753 +0xdb
	k8s.io/api/core/v1.(*Pod).DeepCopy(...)
		/go/src/github.com/isovalent/hubble-fgs/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3765
	k8s.io/api/core/v1.(*Pod).DeepCopyObject(0x1359e3ea6008)
		/go/src/github.com/isovalent/hubble-fgs/vendor/k8s.io/api/core/v1/zz_generated.deepcopy.go:3771 +0x3a
	sigs.k8s.io/controller-runtime/pkg/cache/internal.(*CacheReader).Get(0x1359e2fc53c0, {0x1359e61686f0?, 0x0?}, {{0x1359e5fae6c0?, 0x371e878?}, {0x1359e8168f00?, 0x2c19e74?}}, {0x39c48d0, 0x1359e3ea6508}, {0x0, ...})
		/go/src/github.com/isovalent/hubble-fgs/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/cache_reader.go:93 +0x735
	sigs.k8s.io/controller-runtime/pkg/cache.(*informerCache).Get(0x1359e2cfe990, {0x3970948, 0x1359e61686f0}, {{0x1359e5fae6c0?, 0x371e878?}, {0x1359e8168f00?, 0x2c19e74?}}, {0x39c48d0, 0x1359e3ea6508}, {0x0, ...})
		/go/src/github.com/isovalent/hubble-fgs/vendor/sigs.k8s.io/controller-runtime/pkg/cache/informer_cache.go:79 +0x1ff
	sigs.k8s.io/controller-runtime/pkg/cache.(*delegatingByGVKCache).Get(0x1359e3be9640?, {0x3970948, 0x1359e61686f0}, {{0x1359e5fae6c0?, 0x2e42da0?}, {0x1359e8168f00?, 0x0?}}, {0x39c48d0, 0x1359e3ea6508}, {0x0, ...})
		/go/src/github.com/isovalent/hubble-fgs/vendor/sigs.k8s.io/controller-runtime/pkg/cache/delegating_by_gvk_cache.go:45 +0x103
	sigs.k8s.io/controller-runtime/pkg/client.(*client).Get(0x1359e2cd5e60, {0x3970948, 0x1359e61686f0}, {{0x1359e5fae6c0?, 0x1359e5a0d998?}, {0x1359e8168f00?, 0x7f169c3e1288?}}, {0x39c48d0, 0x1359e3ea6508}, {0x0, ...})
		/go/src/github.com/isovalent/hubble-fgs/vendor/sigs.k8s.io/controller-runtime/pkg/client/client.go:373 +0x21c
	github.com/isovalent/hubble-fgs/pkg/workloadid.(*State).Reconcile(0x1359e38daea0, {0x3970948, 0x1359e61686f0}, {{{0x1359e5fae6c0?, 0x2000000000010?}, {0x1359e8168f00?, 0x57888d?}}})
		/go/src/github.com/isovalent/hubble-fgs/pkg/workloadid/hooks.go:33 +0xca
	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0x1359e615c680, {0x3970948?, 0x1359e61686f0}, {{{0x1359e5fae6c0, 0x0?}, {0x1359e8168f00?, 0x0?}}})
		/go/src/github.com/isovalent/hubble-fgs/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:222 +0x1ab
	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x39c4b00, {0x3970980, 0x1359e3be6a00}, {{{0x1359e5fae6c0, 0x8}, {0x1359e8168f00, 0x24}}}, 0x0)
		/go/src/github.com/isovalent/hubble-fgs/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:479 +0x39b
	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x39c4b00, {0x3970980, 0x1359e3be6a00})
		/go/src/github.com/isovalent/hubble-fgs/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:438 +0x1f8
	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1.1()
		/go/src/github.com/isovalent/hubble-fgs/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:313 +0x85
	created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func1 in goroutine 537
		/go/src/github.com/isovalent/hubble-fgs/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:309 +0x26b

Signed-off-by: Mahe Tardy <mahe.tardy@gmail.com>