hubble-fgs: update agw, fwa, tetragon to reflect latest IPA changes
After IPA update we need to also update the export defines.

pkg/model/server/export.go:85:25: undefined: graphV1.Emitter_EMITTER_TETRAGON

to use the new format {name, version}

The cross product of src+dst+ports created too many rules. In one example
ruleset it was the difference between 8884 rules and 1.2M rules. To fix
this we now push the ports as one object avoding corss product with the
prots altogether.

Signed-off-by: John Fastabend <john.fastabend@gmail.com>