hubble-fgs: remove unused pid from kprobe ret prog
Fix compiler error/warning with clang latest.

process/bpf_generic_retkprobe.c:39:8: error: variable 'pid' set but not used [-Werror,-Wunused-but-set-variable]
        __u32 pid, ppid;
              ^
1 error generated.

Signed-off-by: John Fastabend <john.fastabend@gmail.com>