hubble-fgs: TLS CI tests are failing on errors reading JSON file
The CI TLS tests may fail, but when checking the JSON artifact it has
the expected events. The go runner gives an error like this,

- FAIL: TestTCTls12 (21.38s)
    sockmap_test.go:196:
        	Error Trace:	sockmap_test.go:196
        	Error:      	Received unexpected error:
        	            	invalid character 'R' looking for beginning of value
        	Test:       	TestTCTls12
    sockmap_test.go:197:
        	Error Trace:	sockmap_test.go:197
        	Error:      	Should be true
        	Test:       	TestTCTls12

this is an error from the JSON unmarshal code. Instead of failing when we get
this error lets do the retry logic we have similar to if we hit EOF or are
simply missing an event. This will then wait the delay and retry. Looking
at the logs indicate this always happened on the first iteration of reading
the file.

Signed-off-by: John Fastabend <john.fastabend@gmail.com>