pkg/testutils: fix racy StartSimpleHTTPServer
So we detected this issue happening sometimes in the tests:

--- FAIL: TestProcessTree (6.97s)
    --- FAIL: TestProcessTree/DNSPolicy (0.01s)
        server_test.go:314:
            	Error Trace:	/host/hubble-fgs/pkg/model/server/server_test.go:314
            	Error:      	Received unexpected error:
            	            	exit status 7
            	Test:       	TestProcessTree/DNSPolicy

I couldn't reproduce but suppose the issue was that curl was making the
request while the Go HTTP server was not ready yet. Let's use httptest
that is written so that Start() returns when the server is ready to take
connections.

Signed-off-by: Mahe Tardy <mahe.tardy@gmail.com>