fim: disable TestFileFsTypeMatch and other tests for >= 6.19
Disable TestFileFsTypeMatch, TestFileGlobMatch, TestMatchOpenrawOps
because they fail on current bpf-next (7.0) with:

file_perfring_test.go:362:
    	Error Trace:	/host/hubble-fgs/pkg/sensors/file/file_perfring_test.go:362
    	Error:      	Received unexpected error:
    	            	sensor fim_sensor_1 from collection file-monitoring-fs-type failed to load: failed prog /host/hubble-fgs/bpf/objs/fexit_sys_open.o kern_version 458752 loadInstance: opening collection '/host/hubble-fgs/bpf/objs/fexit_sys_open.o' failed: program io_openat2: load program: invalid argument: nonzero insn_off 1554 for the first func info recordprocessed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
    	Test:       	TestFileFsTypeMatch

    file_perfring_test.go:486:
                Error Trace:    /home/kkourt/src/hubble-fgs/pkg/sensors/file/file_perfring_test.go:486
                Error:          Received unexpected error:
                                sensor fim_sensor_1 from collection file-monitoring-glob failed to load: failed prog bpf/objs/fexit_sys_open.o kern_version 458752 loadInstance: opening collection 'bpf/objs/fexit_sys_open.o' failed: program io_openat2: load program: invalid argument: nonzero insn_off 1554 for the first func info recordprocessed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
                Test:           TestFileGlobMatch

file_perfring_test.go:940:
                Error Trace:    /home/kkourt/src/hubble-fgs/pkg/sensors/file/file_perfring_test.go:940
                Error:          Received unexpected error:
                                sensor fim_sensor_3 from collection file-monitoring-openraw failed to load: failed prog bpf/objs/fexit_sys_open.o kern_version 458752 loadInstance: opening collection 'bpf/objs/fexit_sys_open.o' failed: program io_openat2: load program: invalid argument: nonzero insn_off 1554 for the first func info recordprocessed 0 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0
                Test:           TestMatchOpenrawOps

Signed-off-by: Kornilios Kourtis <kornilios@isovalent.com>