fim: Fix a flake in TestPrefixTree1
We are seeing an error similar to:
--- FAIL: TestPrefixTree1 (0.00s)
    prefix_test.go:40:
        	Error Trace:	/home/apapag/hubble-fgs/pkg/sensors/file/utils/prefix_test.go:40
        	Error:      	Not equal:
        	            	expected: []file.PrefixSuffixFileMatchers{file.PrefixSuffixFileMatchers{WalkPrefix:"/home", Matchers:map[file.PrefixSuffixFileMatcherRule]struct {}{file.PrefixSuffixFileMatcherRule{Matcher:file.PrefixSuffixFileMatcher{Prefix:"/home/", Suffix:".txt"}, Rule:0x0}:struct {}{}, file.PrefixSuffixFileMatcherRule{Matcher:file.PrefixSuffixFileMatcher{Prefix:"/home/apapag/", Suffix:".sh"}, Rule:0x1}:struct {}{}, file.PrefixSuffixFileMatcherRule{Matcher:file.PrefixSuffixFileMatcher{Prefix:"/home/pizza/", Suffix:".go"}, Rule:0x2}:struct {}{}}}, file.PrefixSuffixFileMatchers{WalkPrefix:"/sys/kernel", Matchers:map[file.PrefixSuffixFileMatcherRule]struct {}{file.PrefixSuffixFileMatcherRule{Matcher:file.PrefixSuffixFileMatcher{Prefix:"/sys/kernel/", Suffix:""}, Rule:0x3}:struct {}{}}}}
        	            	actual  : []file.PrefixSuffixFileMatchers{file.PrefixSuffixFileMatchers{WalkPrefix:"/sys/kernel", Matchers:map[file.PrefixSuffixFileMatcherRule]struct {}{file.PrefixSuffixFileMatcherRule{Matcher:file.PrefixSuffixFileMatcher{Prefix:"/sys/kernel/", Suffix:""}, Rule:0x3}:struct {}{}}}, file.PrefixSuffixFileMatchers{WalkPrefix:"/home", Matchers:map[file.PrefixSuffixFileMatcherRule]struct {}{file.PrefixSuffixFileMatcherRule{Matcher:file.PrefixSuffixFileMatcher{Prefix:"/home/", Suffix:".txt"}, Rule:0x0}:struct {}{}, file.PrefixSuffixFileMatcherRule{Matcher:file.PrefixSuffixFileMatcher{Prefix:"/home/apapag/", Suffix:".sh"}, Rule:0x1}:struct {}{}, file.PrefixSuffixFileMatcherRule{Matcher:file.PrefixSuffixFileMatcher{Prefix:"/home/pizza/", Suffix:".go"}, Rule:0x2}:struct {}{}}}}

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,15 @@
        	            	 ([]file.PrefixSuffixFileMatchers) (len=2) {
        	            	+ (file.PrefixSuffixFileMatchers) {
        	            	+  WalkPrefix: (string) (len=11) "/sys/kernel",
        	            	+  Matchers: (map[file.PrefixSuffixFileMatcherRule]struct {}) (len=1) {
        	            	+   (file.PrefixSuffixFileMatcherRule) {
        	            	+    Matcher: (file.PrefixSuffixFileMatcher) {
        	            	+     Prefix: (string) (len=12) "/sys/kernel/",
        	            	+     Suffix: (string) ""
        	            	+    },
        	            	+    Rule: (uint32) 3
        	            	+   }: (struct {}) {
        	            	+   }
        	            	+  }
        	            	+ },
        	            	  (file.PrefixSuffixFileMatchers) {
        	            	@@ -4,10 +17,2 @@
        	            	   Matchers: (map[file.PrefixSuffixFileMatcherRule]struct {}) (len=3) {
        	            	-   (file.PrefixSuffixFileMatcherRule) {
        	            	-    Matcher: (file.PrefixSuffixFileMatcher) {
        	            	-     Prefix: (string) (len=6) "/home/",
        	            	-     Suffix: (string) (len=4) ".txt"
        	            	-    },
        	            	-    Rule: (uint32) 0
        	            	-   }: (struct {}) {
        	            	-   },
        	            	    (file.PrefixSuffixFileMatcherRule) {
        	            	@@ -27,14 +32,9 @@
        	            	    }: (struct {}) {
        	            	-   }
        	            	-  }
        	            	- },
        	            	- (file.PrefixSuffixFileMatchers) {
        	            	-  WalkPrefix: (string) (len=11) "/sys/kernel",
        	            	-  Matchers: (map[file.PrefixSuffixFileMatcherRule]struct {}) (len=1) {
        	            	+   },
        	            	    (file.PrefixSuffixFileMatcherRule) {
        	            	     Matcher: (file.PrefixSuffixFileMatcher) {
        	            	-     Prefix: (string) (len=12) "/sys/kernel/",
        	            	-     Suffix: (string) ""
        	            	+     Prefix: (string) (len=6) "/home/",
        	            	+     Suffix: (string) (len=4) ".txt"
        	            	     },
        	            	-    Rule: (uint32) 3
        	            	+    Rule: (uint32) 0
        	            	    }: (struct {}) {
        	Test:       	TestPrefixTree1

The main reason for that is that we use assert.Equal to compare 2 slices with 2 elements
each of them. As this is related to the order, this test may fail in some cases.

In the implementation we don't care about the order so we change the use of assert.Equal
to a check for len == 2 and 2 calls of assert.Contains. This seems to fix the flake.

Signed-off-by: Anastasios Papagiannis <anastasios.papagiannis@isovalent.com>