hubble-fgs: Get rid of unused variable/helper call
New clang complains with:

  networking/bpf_tcpmon.c:37:18: error: variable 'pid' set but not used [-Werror,-Wunused-but-set-variable]
          __u32 ppid = 0, pid = 0, zero = 0;

Removing unused pid variable and helper call.

Signed-off-by: Jiri Olsa <jolsa@kernel.org>