nop test: do not use observer
There is no need to use the observer if we just want to check that
sensors load. Simplify the nop test.

This is meant to fix some test flakes that were observed in CI.

See the failure below:

fatal error: sync: Unlock of unlocked RWMutex
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x30bd860]

goroutine 21 [running]:
sync.fatal({0x43a552b?, 0xc000cfefc0?})
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/runtime/panic.go:1007 +0x18
sync.(*RWMutex).Unlock(0xc000eca168)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/sync/rwmutex.go:208 +0x45
panic({0x3e01a00?, 0x62bdfc0?})
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/runtime/panic.go:770 +0x132
github.com/cilium/tetragon/pkg/sensors.(*Sensor).IsLoaded(0xc001cde320?)
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/sensors/sensors.go:75
github.com/cilium/tetragon/pkg/sensors.(*collection).load(0xc00401e960, {0xc000cb2760, 0x19})
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/sensors/collection.go:100 +0xab
github.com/cilium/tetragon/pkg/sensors.(*handler).addTracingPolicy(0xc000cbdb30, 0xc002638f00)
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/sensors/handler.go:142 +0x4cb
github.com/cilium/tetragon/pkg/sensors.startSensorManager.func1()
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/sensors/manager.go:82 +0x3ec
created by github.com/cilium/tetragon/pkg/sensors.startSensorManager in goroutine 20
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/sensors/manager.go:67 +0xe5

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000ee8340, {0x437312d?, 0x0?}, 0x44c4d38)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1750 +0x3ab
testing.runTests.func1(0xc000ee8340)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:2161 +0x37
testing.tRunner(0xc000ee8340, 0xc000e35b78)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1689 +0xfb
testing.runTests(0xc000c45c38, {0x62f0ca0, 0x2, 0x2}, {0x302e?, 0x0?, 0x645c700?})
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:2159 +0x445
testing.(*M).Run(0xc000ef0140)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:2027 +0x68b
github.com/cilium/tetragon/pkg/testutils/sensors.TestSensorsRun(0xc000ef0140, {0x434f36a, 0x9})
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/testutils/sensors/testrun.go:139 +0x4ab
github.com/isovalent/hubble-fgs/pkg/testutils/runner.TestSensorsRun(...)
	/host/hubble-fgs/pkg/testutils/runner/runner.go:36
github.com/isovalent/hubble-fgs/pkg/sensors/nop_test.TestMain(0x43403e6?)
	/host/hubble-fgs/pkg/sensors/nop/nop_test.go:39 +0x47
main.main()
	_testmain.go:87 +0x1b5

goroutine 20 [chan receive]:
github.com/cilium/tetragon/pkg/sensors.(*Manager).AddTracingPolicy(0xc000c440f0, {0x47f6c98, 0x69ebe40}, {0x7fb57ee065a0, 0xc000410008})
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/sensors/manager.go:205 +0x19a
github.com/cilium/tetragon/pkg/observer/observertesthelper.loadObserver({0x481d4b0, 0xc000ee84e0}, {0x47f6c98, 0x69ebe40}, 0x63041a0, {0x7fb57ee065a0, 0xc000410008})
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/observer/observertesthelper/observer_test_helper.go:455 +0x10e
github.com/cilium/tetragon/pkg/observer/observertesthelper.getDefaultObserver({0x481d4b0, 0xc000ee84e0}, {0x47f6c98, 0x69ebe40}, 0x63041a0, {0xc000c21a00, 0x5, 0x8})
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/observer/observertesthelper/observer_test_helper.go:247 +0x25d
github.com/cilium/tetragon/pkg/observer/observertesthelper.GetDefaultObserverWithWatchers({0x481d4b0, 0xc000ee84e0}, {0x47f6c98, 0x69ebe40}, 0x63041a0, {0xc000eca040, 0x3, 0x4})
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/observer/observertesthelper/observer_test_helper.go:295 +0x22c
github.com/cilium/tetragon/pkg/observer/observertesthelper.GetDefaultObserverWithBase({0x481d4b0, 0xc000ee84e0}, {0x47f6c98, 0x69ebe40}, 0x63041a0, {0x43a512b, 0x20}, {0xc000c43800, 0x19}, {0xc001505f28, ...})
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/observer/observertesthelper/observer_test_helper.go:302 +0x1ee
github.com/isovalent/hubble-fgs/pkg/observer/observertesthelper.GetDefaultObserverWithBase({0x481d4b0?, 0xc000ee84e0?}, {0x47f6c98?, 0x69ebe40?}, 0x604?, {0x43a512b?, 0x18c4ea0?}, {0xc000c43800?, 0x6344500?}, {0xc001505f28, ...})
	/host/hubble-fgs/pkg/observer/observertesthelper/observer_test_helper.go:56 +0x91
github.com/isovalent/hubble-fgs/pkg/sensors/nop_test.TestNopSensorSmoke(0xc000ee84e0)
	/host/hubble-fgs/pkg/sensors/nop/nop_test.go:65 +0x192
testing.tRunner(0xc000ee84e0, 0x44c4d38)
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/testing/testing.go:1742 +0x390

goroutine 22 [select]:
github.com/cilium/tetragon/pkg/process.(*Cache).cacheGarbageCollector.func1()
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/process/cache.go:46 +0xf1
created by github.com/cilium/tetragon/pkg/process.(*Cache).cacheGarbageCollector in goroutine 20
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/process/cache.go:42 +0xe7

goroutine 23 [select]:
github.com/cilium/tetragon/pkg/eventcache.(*Cache).loop(0xc000c21a80)
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/eventcache/eventcache.go:170 +0x125
created by github.com/cilium/tetragon/pkg/eventcache.NewWithTimer in goroutine 20
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/eventcache/eventcache.go:239 +0x167

goroutine 24 [runnable]:
strings.Trim({0x3e2f746?, 0x4?}, {0x4352f8b?, 0xa?})
	/root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64/src/strings/strings.go:891 +0x16d
google.golang.org/protobuf/internal/impl.(*MessageInfo).makeStructInfo(0xc000c5ccd8, {0x482bb58, 0x4167fa0})
	/host/hubble-fgs/vendor/google.golang.org/protobuf/internal/impl/message.go:180 +0xf45
google.golang.org/protobuf/internal/impl.(*MessageInfo).initOnce(0xc000c5ccd8)
	/host/hubble-fgs/vendor/google.golang.org/protobuf/internal/impl/message.go:89 +0x14c
google.golang.org/protobuf/internal/impl.(*MessageInfo).init(...)
	/host/hubble-fgs/vendor/google.golang.org/protobuf/internal/impl/message.go:72
google.golang.org/protobuf/internal/impl.(*messageState).Range(0xc00401e8a0, 0xc003f77270)
	/host/hubble-fgs/vendor/google.golang.org/protobuf/internal/impl/message_reflect_gen.go:46 +0x4c
google.golang.org/protobuf/internal/order.RangeFields({0x7fb57ed7a278, 0xc00401e8a0}, 0x44c9178, 0xc003f5de00)
	/host/hubble-fgs/vendor/google.golang.org/protobuf/internal/order/range.go:50 +0x16f
google.golang.org/protobuf/encoding/protojson.encoder.marshalMessage({0xc003f5ddb0, {{}, 0x0, {0x0, 0x0}, 0x0, 0x1, 0x0, 0x0, 0x0, ...}}, ...)
	/host/hubble-fgs/vendor/google.golang.org/protobuf/encoding/protojson/encode.go:261 +0x478
google.golang.org/protobuf/encoding/protojson.MarshalOptions.marshal({{}, 0x0, {0x0, 0x0}, 0x0, 0x1, 0x0, 0x0, 0x0, {0x47f72d0, ...}}, ...)
	/host/hubble-fgs/vendor/google.golang.org/protobuf/encoding/protojson/encode.go:164 +0x1c5
google.golang.org/protobuf/encoding/protojson.MarshalOptions.Marshal(...)
	/host/hubble-fgs/vendor/google.golang.org/protobuf/encoding/protojson/encode.go:132
github.com/cilium/tetragon/pkg/encoder.(*ProtojsonEncoder).Encode(0xc000f042f0, {0x42d6120?, 0xc00401e8a0?})
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/encoder/encoder.go:151 +0x65
github.com/cilium/tetragon/pkg/exporter.(*Exporter).Send(0xc0005b6060?, 0xc00401e8a0)
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/exporter/exporter.go:62 +0x5c
github.com/cilium/tetragon/pkg/server.(*Server).GetEventsWG(0xc000ede190, 0xc00050e180, {0x48042c0, 0xc000ede1e0}, {0x47bed20, 0xc000cbddd0}, 0xc000b56260)
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/server/server.go:202 +0x944
github.com/cilium/tetragon/pkg/exporter.(*Exporter).Start.func1()
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/exporter/exporter.go:48 +0x3f
created by github.com/cilium/tetragon/pkg/exporter.(*Exporter).Start in goroutine 20
	/host/hubble-fgs/vendor/github.com/cilium/tetragon/pkg/exporter/exporter.go:47 +0xb0

Signed-off-by: Kornilios Kourtis <kornilios@gmail.com>