hubble-fgs: build error introduced with merge conflict
networking/l3/tcp/bpf_tcp_sockops_5_15.c:208:18: error: use of undeclared identifier 'old_state'
                if (tcp_active(old_state))

It appears this instance of old_state did not correctly get changed.

Signed-off-by: John Fastabend <john.fastabend@gmail.com>