hubble-fgs: fix panic when btf file is incorrect
If BTF file is specified but missing we try to write to it with BTF
helpers and this causes a panic.

INFO[0000] Read ProcFS /proc/ appended 130/388 entries
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1785e31]

runtime stack:
runtime.throw(0x1bc3dbd, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:704 +0x4ac

goroutine 1 [syscall]:
runtime.cgocall(0x1781510, 0xc0005ef340, 0xd)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0005ef310 sp=0xc0005ef2d8 pc=0x40c43b
github.com/covalentio/hubble-fgs/pkg/bpf._Cfunc_addEnumBtf(0x0, 0x7f7980000ca0, 0x1, 0x0)
	_cgo_gotypes.go:144 +0x4d fp=0xc0005ef340 sp=0xc0005ef310 pc=0xa0f38d

We still have a panic if the file exists but is corrupted or otherwise not
a BTF file. This fix needs to go to libbpf though.

Signed-off-by: John Fastabend <john.fastabend@gmail.com>